### ISSUE TITLE
No facets seen on the UI search page

### ISSUE THREAD

**Issue by ghost** [MarkLogicUniversity/top-songs#1]
I want to see the facets . Please let me know how to see the facets and as there are no instructions can somebody help me how to load data etc .

**Comment by gregnist** [comment]
Hello --

In order to see the facets, you need to have the indexes configured.  There are many ways to do that, for example by hand using the Admin interface, or through deploying a database configuration using the Management API.  Another simple way is to run this script in Query Console, making sure to substitute "YOUR-DATABASE-NAME" with your actual database name where indicated.

(: script to deploy all the index settings for the top-songs application :)
  (: URI Lexicon :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $uri-lex := admin:database-set-uri-lexicon($config, xdmp:database("YOUR-DATABASE-NAME"), fn:true())
  return admin:save-configuration($uri-lex);

  (: Collection Lexicon :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $collection-lex := admin:database-set-collection-lexicon($config, xdmp:database("YOUR-DATABASE-NAME"), fn:true())
  return admin:save-configuration($collection-lex);

  (: Directory Creation: Manual :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $dir-creation := admin:database-set-directory-creation($config, xdmp:database("top-songs-dev"), "manual")
  return admin:save-configuration($dir-creation);

  (: Element Range Indexes :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $rangespec := (
    admin:database-range-element-index(
      "date",
      "http://marklogic.com/MLU/top-songs",
      "week",
      "",
      fn:false()
     ),
     admin:database-range-element-index(
      "string",
      "http://marklogic.com/MLU/top-songs",
      "genre",
      "http://marklogic.com/collation/",
      fn:false()
     ),
     admin:database-range-element-index(
      "string",
      "http://marklogic.com/MLU/top-songs",
      "genre",
      "http://marklogic.com/collation/en/S1/AS/T00BB",
      fn:false()
     ),
     admin:database-range-element-index(
      "string",
      "http://marklogic.com/MLU/top-songs",
      "artist",
      "http://marklogic.com/collation/en/S1/AS/T00BB",
      fn:false()
     ),
     admin:database-range-element-index(
      "string",
      "http://marklogic.com/MLU/top-songs",
      "title",
      "http://marklogic.com/collation/en/S1/AS/T00BB",
      fn:false()
     )
  )
  let $indexes := admin:database-add-range-element-index(
    $config,
    admin:database-get-id($config, "top-songs-dev"),
    $rangespec)
  return admin:save-configuration($indexes);

  (: Attribute Range Indexes :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $rangespec := (
    admin:database-range-element-attribute-index(
      "date",
      "http://marklogic.com/MLU/top-songs",
      "weeks",
      "",
      "last",
      "",
      fn:false()
    )
  )
  let $indexes := admin:database-add-range-element-attribute-index(
    $config,
    admin:database-get-id($config, "YOUR-DATABASE-NAME"),
    $rangespec)
  return admin:save-configuration($indexes);

  (: Word Query - Included Elements :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $wqspec := (
    admin:database-included-element(
      "http://marklogic.com/MLU/top-songs",
      "artist",
      4.0,
      "",
      "",
      ""
    ),
    admin:database-included-element(
      "http://marklogic.com/MLU/top-songs",
      "title",
      4.0,
      "",
      "",
      ""
    ),
    admin:database-included-element(
      "http://marklogic.com/MLU/top-songs",
      "descr",
      0.75,
      "",
      "",
      ""
    )
  )
  let $wq := admin:database-add-word-query-included-element(
    $config,
    admin:database-get-id($config, "YOUR-DATABASE-NAME"),
    $wqspec
  )
  return admin:save-configuration($wq);

  (: Word Query - Excluded Elements :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $wqspec := (
    admin:database-excluded-element(
      "http://marklogic.com/MLU/top-songs",
      "format"
    ),
    admin:database-excluded-element(
      "http://marklogic.com/MLU/top-songs",
      "length"
    )
  )
  let $wq := admin:database-add-word-query-excluded-element(
    $config,
    admin:database-get-id($config, "YOUR-DATABASE-NAME"),
    $wqspec
  )
  return admin:save-configuration($wq);

  (: Field :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $dbid := xdmp:database("YOUR-DATABASE-NAME")
  let $fieldspec := admin:database-field("creator", fn:false() )
  let $field := admin:database-add-field($config, $dbid, $fieldspec)
  return admin:save-configuration($field);

  (: Field - Included Elements :)
  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $dbid := xdmp:database("YOUR-DATABASE-NAME")
  let $fieldspec :=   admin:database-included-element("http://marklogic.com/MLU/top-songs", "artist", 1.0, "", "", "")
  let $field-include := admin:database-add-field-included-element($config, $dbid, "creator", $fieldspec)
  return admin:save-configuration($field-include);

  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $dbid := xdmp:database("YOUR-DATABASE-NAME")
  let $fieldspec :=   admin:database-included-element("http://marklogic.com/MLU/top-songs", "writer", 1.0, "", "", "")
  let $field-include := admin:database-add-field-included-element($config, $dbid, "creator", $fieldspec)
  return admin:save-configuration($field-include);

  xquery version "1.0-ml";
  import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
  let $config := admin:get-configuration()
  let $dbid := xdmp:database("YOUR-DATABASE-NAME")
  let $fieldspec :=   admin:database-included-element("http://marklogic.com/MLU/top-songs", "producer", 1.0, "", "", "")
  let $field-include := admin:database-add-field-included-element($config, $dbid, "creator", $fieldspec)
  return admin:save-configuration($field-include);

  (: Finished :)
  xquery version "1.0-ml";
  "Index Script Completed"

**Comment by ghost** [comment]
Hi gregnist,
Thanks for your reply. I don't know how much I can thank you, but I was expecting someone to help me as I need to build a similar application very soon.
1. I created the eclipse application, I am able to see the home page.
2. At the moment I am getting null pointer exception.
3. I know I haven't created any database and indexes and have not loaded any data 
4. Can you please help me from where do I get the sample songs data.
5. Now if I create the database say TOP-SONG, create range index and upload the data, now it seems I need to configure the port or rest port so that my application knows which port to get connected. Can you please help me with setting up the ports in database and then I can change in the application. Will this be enough.
7. Can you please help me where can I find the link to some configuration documentation as this project seems to have no documentation.
8. Believe me I am very weak in xquery.
9. Thanks again.

**Comment by ghost** [comment]
Hi,
It seems I need to create a database first 'TOP-SONG' as I am getting the error no such database for running the script through the query console

[1.0-ml] XDMP-NOSUCHDB: xdmp:database("TOP-SONG") -- No such database TOP-SONG

Stack Trace
At line 6 column 56:

In xdmp:eval("(: script to deploy all the index settings for the top-songs app...", (), <options xmlns="xdmp:eval"><database>14912833513762509030</database><modules>15574285864046...</options>)

$config := <configuration/>
1. import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
2. let $config := admin:get-configuration()
3. let $uri-lex := admin:database-set-uri-lexicon($config, xdmp:database("TOP-SONG"), fn:true())
4. return admin:save-configuration($uri-lex);

**Comment by ghost** [comment]
Hi gregnist,

Please let me know why we need to create two databases 'TOP-SONG' and 'top-song-dev'.
Now I am getting 

[1.0-ml] ADMIN-DUPLICATECONFIGITEM: (err:FOER0000) Database 'range-element-index' already exists in resource top-songs-dev

**Comment by ghost** [comment]
Hi greenist,
I am getting this error while searching for -'Southern Nights' and I am still not able to see the facets even after setting the range-element-index

ERROR: com.marklogic.training.SearchController - caught exception in search() com.marklogic.client.FailedRequestException: Local message: search failed: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: full-options

**Comment by joecrean** [comment]
you need to run the class LoadOptions.java from your IDE and that will create all the search options you need.

**Comment by ghost** [comment]
Hi joecrean,

Thanks for your help. I ran the LoadOptions.java from Eclipse. It terminated without error which I presume the rest request worked properly with the user and the password.

But I am only able to see the Home search page , am unable to see the facets . I have loaded only one file that is song.xml that comes under the data/song.xml in my database TOP-SONG.

Please help me , what am I missing in the facets configuration. I really need the facets. And searching 'Southern Nights' through the UI it says 'Sorry, no results for your search.' but when I search through Query Console I am able to get the data 
1. Query - cts:search(fn:doc(), cts:word-query("Allen Toussaint") )
2. Results- <title href="http://en.wikipedia.org/wiki/Southern_Nights_(song)" xmlns:ts="http://marklogic.com/MLU/top-songs">
Southern Nights
</title>
<artist href="http://en.wikipedia.org/wiki/Glen_Campbell" xmlns:ts="http://marklogic.com/MLU/top-songs">
Glen Campbell
</artist> .......

Why am I unable to see the facets? Request you to please help , any facets conf I am missing.

**Comment by ghost** [comment]
Hi,
I am able to see 
1.Check your birthday
2.administrator login 
on the left navigational panel and the search text box. No facets.

**Comment by gregnist** [comment]
Try loading an XML document into your database like the one I pasted in below.  The facets are driven by the range indexes, and the range indexes are configured on XML elements or attributes.  This document has those elements or attributes, therefore if you load it, it should generate some facets.  Load it into your database with a URI in the pattern of:

/songs/filename.xml

If your database is configured correctly and you load this document in that format, you should see it in the facets.


<top-song xmlns="http://marklogic.com/MLU/top-songs">
  
  <title href="http://en.wikipedia.org/wiki/Hotel_California_(song)" xmlns:ts="http://marklogic.com/MLU/top-songs">Hotel California</title>
  <artist href="http://en.wikipedia.org/wiki/Eagles" xmlns:ts="http://marklogic.com/MLU/top-songs">Eagles</artist>
  <weeks last="1977-05-07">
    <week>1977-05-07</week>
  </weeks>
  <album url="http://upload.wikimedia.org/wikipedia/en/thumb/2/26/SteelyKnifes.jpg/200px-SteelyKnifes.jpg" uri="/images/Eagles+Hotel-California.jpg">Hotel
  California</album>
  <released>February 1977</released>
  <formats>
    <format>7" single</format>
  </formats>
  <recorded>1976</recorded>
  <genres>
    <genre>Rock</genre>
  </genres>
  <lengths>
    <length>6:31</length>
  </lengths>
  <label>Asylum</label>
  <writers>
    <writer>Don Felder</writer>
    <writer>Glenn Frey</writer>
    <writer>Don Henley</writer>
  </writers>
  <producers>
    <producer>Bill Szymczyk</producer>
  </producers>
  <descr>
    <p>"Hotel California" is the title song from the Eagles' album
    of the same name and was released as a single in early 1977. It
    is one of the best-known songs of the album-oriented rock era.
    Writing credits for the song are shared by Don Felder, Don
    Henley and Glenn Frey. The Eagles' original recording of the
    song features Henley singing the lead vocals and concludes with
    an extended section of electric guitar interplay between Felder
    and Joe Walsh.</p>
    <p>"Hotel California" topped the Billboard Hot 100 singles
    chart for one week in May 1977. Three months after its release,
    the single was certified Gold by the Recording Industry
    Association of America representing 1,000,000 records shipped.
    The Eagles also won the 1977 Grammy Award for Record of the
    Year for "Hotel California" at the 20th Annual Grammy Awards in
    1978.</p>
    <p>In 2009, the song "Hotel California" was certified Platinum
    (Digital Sales Award) by the RIAA for sales of 1,000,000
    digital downloads.</p>
    <p>The song is rated highly in many rock music lists and polls.
    
    <i>Rolling Stone</i>magazine, for example, placed it as the
    49th greatest song of all time. It is also one of The Rock and
    Roll Hall of Fame's 500 Songs that Shaped Rock and Roll. The
    song's guitar solo is ranked 8th on 
    <i>Guitar Magazine'</i>s Top 100 Guitar Solos.</p>
    <p>As one of the group's most popular and well-known songs,
    "Hotel California" has been a concert staple for the band since
    its release; performances of the song appear on the Eagles'
    1980 live album and, in an acoustic version, on the 1994 
    <i>Hell Freezes Over</i>reunion concert CD and video release.
    The "Hell Freezes Over" version is performed using eight
    guitars in total, and has a decidedly Spanish feel to it - with
    Don Felder playing a flamenco-inspired intro. During the band's
    Farewell 1 Tour-Live from Melbourne the song was performed in a
    manner closer to the original album version, but with a trumpet
    interlude in the beginning.</p>
    <p>The song is a playable track on the video game 
    <i>Guitar Hero World Tour</i>.</p>
    <p>The song's lyrics describe the title establishment as a
    luxury resort where "you can check out anytime you like, but
    you can never leave." On the surface, the song tells the tale
    of a weary traveler who becomes trapped in a nightmarish luxury
    hotel that at first appeared inviting and tempting. The song is
    an allegory about hedonism and self-destruction in the Southern
    California music industry of the late 1970s; Don Henley called
    it "our interpretation of the high life in Los Angeles" and
    later reiterated "it's basically a song about the dark
    underbelly of the American dream and about excess in America,
    which is something we knew a lot about." In 2008, Don Felder
    described the origins of the lyrics:</p>
    <p>"Don Henley and Glenn wrote most of the words. All of us
    kind of drove into LA at night. Nobody was from California, and
    if you drive into LA at night... you can just see this glow on
    the horizon of lights, and the images that start running
    through your head of Hollywood and all the dreams that you
    have, and so it was kind of about that... what we started
    writing the song about. Coming into LA... and from that 
    <i>Life In The Fast Lane</i>came out of it, and 
    <i>Wasted Time</i>and a bunch of other songs.":</p>
    <p>The abstract nature of the lyrics has led listeners to their
    own interpretations over the years. In the 1980s, some
    Christian evangelists alleged that "Hotel California" referred
    to a San Francisco hotel purchased by Anton LaVey and converted
    into the Church of Satan. Other rumors suggested that the Hotel
    California was the Camarillo State Mental Hospital. These
    claims have been consistently refuted by the band.</p>
    <p>The term "colitas" in the first stanza of the song is a
    Spanish term for "little tails" and a reference to the buds of
    the Cannabis plant.</p>
    <p>In a 2009 interview, Plain Dealer music critic John Soeder
    asked Don Henley this about the lyrics:</p>
    <p>On "Hotel California," you sing: "So I called up the captain
    / 'Please bring me my wine' / He said, 'We haven't had that
    spirit here since 1969.'" I realize I'm probably not the first
    to bring this to your attention, but wine isn't a spirit. Wine
    is fermented; spirits are distilled. Do you regret that
    lyric?</p>
    <p>Henley responded,</p>
    <p>"Thanks for the tutorial and, no, you're not the first to
    bring this to my attention—and you're not the first to
    completely misinterpret the lyric and miss the metaphor.
    Believe me, I've consumed enough alcoholic beverages in my time
    to know how they are made and what the proper nomenclature is.
    But that line in the song has little or nothing to do with
    alcoholic beverages. It's a sociopolitical statement. My only
    regret would be having to explain it in detail to you, which
    would defeat the purpose of using literary devices in
    songwriting and lower the discussion to some silly and
    irrelevant argument about chemical processes."</p>
    <p>According to Glenn Frey's liner notes for 
    <i>The Very Best of Eagles,</i>the use of the word "steely" in
    the lyric (referring to knives) was a playful nod to band
    Steely Dan, who had included the lyric "Turn up the Eagles, the
    neighbors are listening" in their song "Everything You
    Did."</p>
    <p>Many cover versions of "Hotel California" have been
    released:</p>
    <p>Parodies include:</p>
    <p>
      <span style="white-space:nowrap">"Nel blu dipinto di blu
      (Volare)" ·</span>
      <span style="white-space:nowrap">"Mack the
      Knife" ·</span>
      <span style="white-space:nowrap">"Theme from A Summer
      Place" ·</span>
      <span style="white-space:nowrap">"Moon River" ·</span>
      <span style="white-space:nowrap">"I Left My Heart in San
      Francisco" ·</span>
      <span style="white-space:nowrap">"Days of Wine and
      Roses" ·</span>
      <span style="white-space:nowrap">"The Girl from
      Ipanema" ·</span>
      <span style="white-space:nowrap">"A Taste of
      Honey" ·</span>
      <span style="white-space:nowrap">"Strangers in the
      Night" ·</span>
      <span style="white-space:nowrap">"Up, Up and
      Away" ·</span>
      <span style="white-space:nowrap">"Mrs. Robinson"</span>
    </p>
    <p>
      <span style="white-space:nowrap">"Aquarius/Let the Sunshine
      In" ·</span>
      <span style="white-space:nowrap">"Bridge over Troubled
      Water" ·</span>
      <span style="white-space:nowrap">"It's Too
      Late" ·</span>
      <span style="white-space:nowrap">"The First Time Ever I Saw
      Your Face" ·</span>
      <span style="white-space:nowrap">"Killing Me Softly with His
      Song" ·</span>
      <span style="white-space:nowrap">"I Honestly Love
      You" ·</span>
      <span style="white-space:nowrap">"Love Will Keep Us
      Together" ·</span>
      <span style="white-space:nowrap">"This
      Masquerade" ·</span>
      <span style="white-space:nowrap">"
      <strong class="selflink">
Hotel California
</strong>" ·</span>
      <span style="white-space:nowrap">"Just the Way You
      Are"</span>
    </p>
    <p>
      <span style="white-space:nowrap">"What a Fool
      Believes" ·</span>
      <span style="white-space:nowrap">"Sailing" ·</span>
      <span style="white-space:nowrap">"Bette Davis
      Eyes" ·</span>
      <span style="white-space:nowrap">"Rosanna" ·</span>
      <span style="white-space:nowrap">"Beat It" ·</span>
      <span style="white-space:nowrap">"What's Love Got to Do with
      It" ·</span>
      <span style="white-space:nowrap">"We Are the
      World" ·</span>
      <span style="white-space:nowrap">"Higher Love" ·</span>
      <span style="white-space:nowrap">"Graceland" ·</span>
      <span style="white-space:nowrap">"Don't Worry, Be
      Happy"</span>
    </p>
    <p>
      <span style="white-space:nowrap">"Wind Beneath My
      Wings" ·</span>
      <span style="white-space:nowrap">"Another Day in
      Paradise" ·</span>
      <span style="white-space:nowrap">
      "Unforgettable" ·</span>
      <span style="white-space:nowrap">"Tears in
      Heaven" ·</span>
      <span style="white-space:nowrap">"I Will Always Love
      You" ·</span>
      <span style="white-space:nowrap">"All I Wanna
      Do" ·</span>
      <span style="white-space:nowrap">"Kiss from a
      Rose" ·</span>
      <span style="white-space:nowrap">"Change the
      World" ·</span>
      <span style="white-space:nowrap">"Sunny Came
      Home" ·</span>
      <span style="white-space:nowrap">"My Heart Will Go On"</span>
    </p>
    <p>
      <span style="white-space:nowrap">"Smooth" ·</span>
      <span style="white-space:nowrap">"Beautiful
      Day" ·</span>
      <span style="white-space:nowrap">"Walk On" ·</span>
      <span style="white-space:nowrap">"Don't Know
      Why" ·</span>
      <span style="white-space:nowrap">"Clocks" ·</span>
      <span style="white-space:nowrap">"Here We Go
      Again" ·</span>
      <span style="white-space:nowrap">"Boulevard of Broken
      Dreams" ·</span>
      <span style="white-space:nowrap">"Not Ready to Make
      Nice" ·</span>
      <span style="white-space:nowrap">"Rehab" ·</span>
      <span style="white-space:nowrap">"Please Read the
      Letter"</span>
    </p>
    <p>
      <span style="white-space:nowrap">"Use Somebody"</span>
    </p>
  </descr>
</top-song>

**Comment by gregnist** [comment]
Try loading an XML document into your database like the one I pasted in below. The facets are driven by the range indexes, and the range indexes are configured on XML elements or attributes. This document has those elements or attributes, therefore if you load it, it should generate some facets. Load it into your database with a URI in the pattern of:

/songs/filename.xml

If your database is configured correctly and you load this document in that format, you should see it in the facets.

![image](https://cloud.githubusercontent.com/assets/1749707/5963388/c85c32e8-a7b9-11e4-943b-dbce196561dd.png)

**Comment by ghost** [comment]
Hi,
I created an application using app-builder using the same database . Please find the link to the screen shot , here I am able to see the facets.
Facets- artist,genre,last,title and week can be seen.
https://cloud.githubusercontent.com/assets/3964763/5963524/2759d620-a813-11e4-8a1b-b83628d602b0.png

**Comment by ghost** [comment]
Hi greenist and joecrean,

Don't know how to thank you guys. After following your instructions and trying and trying and trying at last I am able to see the FACETS, which is a dream come true.
Please find the working top-songs working facets below.
It's awesome. Thanks you guys once again.
https://cloud.githubusercontent.com/assets/3964763/5964083/4d157956-a817-11e4-8a05-981168042296.png

**Comment by ghost** [comment]
Hi ,
I still need a few clarifications.
1. There is still no pagination seen as seen in http://mlu.marklogic.com/top-songs/index.xqy .
2. 1 to 10 of 1836 seen on top of sort by label is not seen.
3. The facets count are not seen inside square [] brackets such as the beatles [19] as seen http://mlu.marklogic.com/top-songs/index.xqy .

Is it implemented or I need to add these features.
Please let me know.

**Comment by gregnist** [comment]
How many documents are in your database?  If you have less than 10 song documents in there, you won't see pagination.

I don't believe the facet numbers are displayed in the Java version of the app, but you could easily add that by working with the JSPs.  That data that you need to include it would be present in the search response.

**Comment by ghost** [comment]
I have only 1 document. Thanks gregnist for your update , will add it and the bracket for the facet count.
Is there a link to the source code of this http://mlu.marklogic.com/top-songs/index.xqy.
I feel this spring java application for Marklogic will be helpful for those familar with java/jsp/spring as I see most of the marklogic examples are in xquery.

**Comment by gregnist** [comment]
If you're looking for a great Java example that is a full functioning app in a 3 tiered architecture (AngularJS, Java Spring, MarkLogic), with enterprise features, and automated deployment and testing, you should check out Samplestack.  Its available on the MarkLogic Github site, has good documentation to get you started, and also has the facets that you seem to be really interested in learning about!

**Comment by ghost** [comment]
Thanks
