### ISSUE TITLE
How to accomodate .SGM and .XML files in search applications

### ISSUE THREAD

**Issue by ghost** [MarkLogicUniversity/top-songs#6]
Hi,
I have adapted Topsongs code to build a search application based on my proprietary data in xml format.
I have built Java classes based on my xml data . Everything was working fine then.

Now comes a big surprise where files ending with .SGM are included and I need to load these files to Marklogic and still search these files.

These .SGM files are completely different from the xml files but how do I build the Java classes which could contain both elements from .SGM and .XML files .
I created an xsd file from xml files and then generated the java classes.
Now what do I do can some suggest me a way to get this application working.

Thanks

**Comment by joecrean** [comment]
MarkLogic does not support SGML directly. Customers with SGML normally take the step to convert it XML firstly. sorry.

**Comment by ghost** [comment]
Thanks joecrean .

**Comment by ghost** [comment]
Hi Joecrean,
Can you please confirm this link which says marklogic support SGML 
http://www.businesswire.com/news/home/20040329005782/en/Mark-Logic-Unveils-Breakthrough-Content-Database-Content#.VRpPWeHdk9M

**Comment by ghost** [comment]
Thanks joe crean
