### ISSUE TITLE
Problems loading options with LoadOptions.java

### ISSUE THREAD

**Issue by ghost** [MarkLogicUniversity/top-songs#8]
Hi,
I am getting this error while loading the chart-options.xml through LoadOptions.java,  the error I am getting is given below .  I have attached images

Please help

[2015.04.02 16:23:15, 340]: DEBUG - Putting /config/query/chart-options 
[2015.04.02 16:23:15, 606]:  ERROR - Exception : com.marklogic.client.FailedRequestException: Local message: /config/query write failed: Precondition Failed. Server Message: RESTAPI-EMPTYBODY (err:FOER0000): Empty POST or PUT body 
[2015.04.02 16:23:15, 606]: INFO - Releasing connection 
[2015.04.02 16:23:15, 618]: DEBUG - Releasing connection

![options](https://cloud.githubusercontent.com/assets/3964763/6962972/61ef6474-d957-11e4-8dd8-16f6de12c186.png)
 for range element index setting for genre and the chart-options.xml 

![genre](https://cloud.githubusercontent.com/assets/3964763/6962841/41ba13d0-d956-11e4-92c0-b45a8ee4a22c.jpg)

**Comment by ghost** [comment]
Is it because that I am using database credentials and have not created rest admin user

**Comment by gregnist** [comment]
In order to create query options, when creating your database client, you should authenticate as a user who has the rest-admin role.

**Comment by ghost** [comment]
Thanks gregnist, I was using database credentials when Marklogic Server prompts the user the first time server starts I didn't create  a rest-admin role. Will try out .

**Comment by gregnist** [comment]
Please keep in mind that the rest-admin role is created when you install and initialize MarkLogic.  You just need to assign the role to the user that you are using when creating your database client.

**Comment by ghost** [comment]
Thanks , will keep that in mind.
